[package]
name = "ctt-pallet-members"
version = "2.0.0"
repository = 'https://github.com/CTT-block-chain/substrate.git'
authors = ["ctt-dev"]
edition = "2018"
license = "GPL-3.0-or-later"
description = "CTT members module"

[package.metadata.substrate]
categories = [
	"pallet"
]
compatibility_version = "2.0.0"

[features]
default = ['std']
std = [
    'parity-scale-codec/std',
    'frame-support/std',
    'frame-system/std',
    'sp-runtime/std',
    "primitives/std",
    "serde",
]

[dependencies]
serde = { version = "1.0.101", features = ["derive"], optional = true }
parity-scale-codec = { version = "1.3.1", features = ["derive"], default-features = false }
frame-support = { version = "2.0.0", default-features = false, path = "../../../../frame/support" }
frame-system = { version = "2.0.0", default-features = false, path = "../../../../frame/system" }
sp-runtime = { version = "2.0.0", default-features = false, path = "../../../../primitives/runtime" }
sp-std = { version = "2.0.0", default-features = false, path = "../../../../primitives/std" }
sp-core = { version = "2.0.0", default-features = false, path = "../../../../primitives/core" }
primitives = { package = "ctt-primitives", path = "../../primitives", default-features = false }
pallet-balances = { version = "2.0.0", default-features = false, path = "../../../../frame/balances" }

[dev-dependencies]
sp-core = { version = "2.0.0", default-features = false, path = "../../../../primitives/core" }
sp-io = { version = "2.0.0", default-features = false, path = "../../../../primitives/io" }
