"""add stages_authors

Revision ID: 253368e0ad13
Revises: d776709ed45b
Create Date: 2021-07-03 18:15:39.421074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '253368e0ad13'
down_revision = 'd776709ed45b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
