"""change nickname

Revision ID: 2b2e36fad26f
Revises: e5df400dcde4
Create Date: 2021-06-27 18:53:13.595432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b2e36fad26f'
down_revision = 'e5df400dcde4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
