"""update author db

Revision ID: 2b6e4b79d768
Revises: 2b2e36fad26f
Create Date: 2021-07-01 21:34:04.372587

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2b6e4b79d768'
down_revision = '2b2e36fad26f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('chain_address', sa.String(length=300), nullable=True))
    op.drop_column('authors', 'token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('token', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('authors', 'chain_address')
    # ### end Alembic commands ###
