"""update author db

Revision ID: 40049e5b8000
Revises: 401f81e76951
Create Date: 2021-07-02 17:36:24.542630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40049e5b8000'
down_revision = '401f81e76951'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
