"""update author db

Revision ID: 401f81e76951
Revises: 2b6e4b79d768
Create Date: 2021-07-02 17:22:00.089271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '401f81e76951'
down_revision = '2b6e4b79d768'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
