"""add stages_authors

Revision ID: 40893c285ef5
Revises: 6f1e7ecaa9fd
Create Date: 2021-07-04 22:09:09.258191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40893c285ef5'
down_revision = '6f1e7ecaa9fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
