"""update test

Revision ID: 52dac41a4a5b
Revises: 7a7c6d20b422
Create Date: 2021-06-25 21:15:35.673163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52dac41a4a5b'
down_revision = '7a7c6d20b422'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'test', 'authors', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test', type_='foreignkey')
    op.drop_column('test', 'owner_id')
    # ### end Alembic commands ###
