"""create

Revision ID: 6741e75df428
Revises: 61632731b77a
Create Date: 2021-06-23 19:19:40.445041

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6741e75df428'
down_revision = '61632731b77a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stages_type', table_name='stages')
    op.drop_column('stages', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stages', sa.Column('type', mysql.SMALLINT(), autoincrement=False, nullable=True))
    op.create_index('ix_stages_type', 'stages', ['type'], unique=False)
    # ### end Alembic commands ###
