"""add stages_authors

Revision ID: 6dfa89765f8d
Revises: da9035ddbfac
Create Date: 2021-07-05 01:06:28.422768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dfa89765f8d'
down_revision = 'da9035ddbfac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
