"""add stages_authors

Revision ID: 6f1e7ecaa9fd
Revises: cdd8c82b1f69
Create Date: 2021-07-03 18:45:46.796481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f1e7ecaa9fd'
down_revision = 'cdd8c82b1f69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
