"""add test

Revision ID: 7a7c6d20b422
Revises: a07efc3600c6
Create Date: 2021-06-25 19:36:28.004603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a7c6d20b422'
down_revision = 'a07efc3600c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
