"""add stages_authors

Revision ID: cdd8c82b1f69
Revises: d27963ee5cc1
Create Date: 2021-07-03 18:41:41.131811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdd8c82b1f69'
down_revision = 'd27963ee5cc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stages_authors_author_id', table_name='stages_authors')
    op.drop_index('ix_stages_authors_stage_id', table_name='stages_authors')
    op.create_foreign_key(None, 'stages_authors', 'stages', ['stage_id'], ['id'])
    op.create_foreign_key(None, 'stages_authors', 'authors', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stages_authors', type_='foreignkey')
    op.drop_constraint(None, 'stages_authors', type_='foreignkey')
    op.create_index('ix_stages_authors_stage_id', 'stages_authors', ['stage_id'], unique=False)
    op.create_index('ix_stages_authors_author_id', 'stages_authors', ['author_id'], unique=False)
    # ### end Alembic commands ###
