"""add stages_authors

Revision ID: d27963ee5cc1
Revises: 253368e0ad13
Create Date: 2021-07-03 18:18:09.075143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd27963ee5cc1'
down_revision = '253368e0ad13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
