"""add stages_authors

Revision ID: d776709ed45b
Revises: eef8f28e64dc
Create Date: 2021-07-03 17:46:48.895761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd776709ed45b'
down_revision = 'eef8f28e64dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_stages_authors_author_id'), 'stages_authors', ['author_id'], unique=False)
    op.create_index(op.f('ix_stages_authors_stage_id'), 'stages_authors', ['stage_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stages_authors_stage_id'), table_name='stages_authors')
    op.drop_index(op.f('ix_stages_authors_author_id'), table_name='stages_authors')
    # ### end Alembic commands ###
