"""add stages_authors

Revision ID: d90c196654c9
Revises: e13394201510
Create Date: 2021-07-05 01:27:04.617975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd90c196654c9'
down_revision = 'e13394201510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
