"""add stages_authors

Revision ID: da9035ddbfac
Revises: 40893c285ef5
Create Date: 2021-07-05 00:56:45.426105

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'da9035ddbfac'
down_revision = '40893c285ef5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('stages_authors')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stages_authors',
    sa.Column('stage_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('author_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], name='stages_authors_ibfk_2'),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], name='stages_authors_ibfk_1'),
    sa.PrimaryKeyConstraint('stage_id', 'author_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('hotel')
    # ### end Alembic commands ###
