"""add stages_authors

Revision ID: eef8f28e64dc
Revises: 40049e5b8000
Create Date: 2021-07-03 17:11:51.118873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eef8f28e64dc'
down_revision = '40049e5b8000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stages_authors',
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('stage_id', 'author_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stages_authors')
    # ### end Alembic commands ###
